const angle_details_left = {
  block_id: 'angle_details_left',
  block_header: 'Hip Angle Details - Left',
  block_description: 'Details about the Angle of the Hip',
  enabled: false,
  required: false,
  questions: [
    {
      id: 'center_edge_left',
      question_header: 'Left Center Edge Angle',
      question_desc: 'Enter the Left Center Edge Angle to the Sourcil',
      enabled: true,
      required: false,
      type: 'FR',
      fr_type: 'number',
      value: [],
    },
    {
      id: 'center_sourcil_left',
      question_header: 'Left Center Edge Angle',
      question_desc: 'Enter the Left Center Edge Angle to the Edge',
      enabled: true,
      required: false,
      type: 'FR',
      fr_type: 'number',
      value: [],
    },
    {
      id: 'alpha_left',
      question_header: 'Left Alpha Angle',
      question_desc: 'Enter Left Side Alpha Angle',
      enabled: true,
      required: false,
      type: 'FR',
      fr_type: 'number',
      value: [],
    },
    {
      id: 'left_femoral_version',
      question_header: 'Left Femoral Version',
      question_desc: 'Enter the Left Femoral Version',
      enabled: true,
      required: false,
      type: 'FR',
      fr_type: 'number',
      value: [],
    },
    {
      id: 'left_femoral_version_type',
      question_header: 'Left Femoral Version',
      question_desc: 'Enter the type Left Femoral Version',
      enabled: true,
      required: false,
      type: 'MC',
      options: [
        { value: 'CT', children: [], blocks_enabled: [] },
        { value: 'MRI', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'left_tonnis_angle',
      question_header: 'Left Tonnis Angle',
      question_desc: 'Enter the Left Tonnis Angle',
      enabled: true,
      required: false,
      type: 'FR',
      fr_type: 'number',
      value: [],
    },
  ],
};

module.exports = angle_details_left;
