const basic_details = {
  block_id: 'basic_details',
  block_header: 'Pre-Screening',
  block_description: "basic details about what you're looking for",
  enabled: true,
  required: true,
  questions: [
    {
      id: 'own_car_yn',
      question_header: 'Do you already own a car?',
      question_desc: '',
      enabled: true,
      required: true,
      type: 'MC',
      options: [
        {
          value: 'Yes',
          children: [],
          blocks_enabled: ['own_car_specs'],
        },
        { value: 'No', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'new_used_car',
      question_header: 'Are you looking for a new car or a used car?',
      question_desc: '(yes or no)',
      enabled: true,
      required: true,
      type: 'MC',
      options: [
        {
          value: 'New Car',
          children: [],
          blocks_enabled: [],
        },
        { value: 'Used Car', children: [], blocks_enabled: [] },
      ],
      value: [],
    },

    {
      id: 'demographics_household_size',
      question_header: 'How many live in your household?',
      question_desc: 'Enter the number of people, including yourself',
      enabled: true,
      required: true,
      type: 'MC',
      options: [
        {
          value: '1',
          children: ['demographics_income_size_1'],
          blocks_enabled: [],
        },
        {
          value: '2',
          children: ['demographics_income_size_2'],
          blocks_enabled: [],
        },
        {
          value: '3',
          children: ['demographics_income_size_3'],
          blocks_enabled: [],
        },
        {
          value: '4',
          children: ['demographics_income_size_4'],
          blocks_enabled: [],
        },
        {
          value: '5',
          children: ['demographics_income_size_5'],
          blocks_enabled: [],
        },
        {
          value: '6',
          children: ['demographics_income_size_6'],
          blocks_enabled: [],
        },
      ],
      value: [],
    },
    {
      id: 'demographics_income_size_1',
      question_header: 'How would you describe your income level?',
      question_desc: 'Choose from one of the categories',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        {
          value: 'Less than $28,980',
          enumVal: 1,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$28,981-$38,640',
          enumVal: 2,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$38,641-$51,520',
          enumVal: 3,
          children: [],
          blocks_enabled: [],
        },
        { value: '$51,521+', enumVal: 4, children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'demographics_income_size_2',
      question_header: 'How would you describe your income level?',
      question_desc: 'Choose from one of the categories',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        {
          value: 'Less than $39,195',
          enumVal: 1,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$39,196-$52,260',
          enumVal: 2,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$52,261-$69,680',
          enumVal: 3,
          children: [],
          blocks_enabled: [],
        },
        { value: '$69,680+', enumVal: 4, children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'demographics_income_size_3',
      question_header: 'How would you describe your income level?',
      question_desc: 'Choose from one of the categories',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        {
          value: 'Less than $49,410',
          enumVal: 1,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$49,411-$65,880',
          enumVal: 2,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$65,881-$87,840',
          enumVal: 3,
          children: [],
          blocks_enabled: [],
        },
        { value: '$87,841+', enumVal: 4, children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'demographics_income_size_4',
      question_header: 'How would you describe your income level?',
      question_desc: 'Choose from one of the categories',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        {
          value: 'Less than $59,625',
          enumVal: 1,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$59,626-$79,500',
          enumVal: 2,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$79,501-$106,000',
          enumVal: 3,
          children: [],
          blocks_enabled: [],
        },
        { value: '$106,601+', enumVal: 4, children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'demographics_income_size_5',
      question_header: 'How would you describe your income level?',
      question_desc: 'Choose from one of the categories',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        {
          value: 'Less than $69,840',
          enumVal: 1,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$69,841-$93,120',
          enumVal: 2,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$93,120-$124,160',
          enumVal: 3,
          children: [],
          blocks_enabled: [],
        },
        { value: '$124,161+', enumVal: 4, children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'demographics_income_size_6',
      question_header: 'How would you describe your income level?',
      question_desc: 'Choose from one of the categories',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        {
          value: 'Less than $80,055',
          enumVal: 1,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$80,056-$106,740',
          enumVal: 2,
          children: [],
          blocks_enabled: [],
        },
        {
          value: '$106,741-$142,320',
          enumVal: 3,
          children: [],
          blocks_enabled: [],
        },
        { value: '$142,321+', enumVal: 4, children: [], blocks_enabled: [] },
      ],
      value: [],
    },
  ],
};

module.exports = basic_details;
