const commute_details = {
  block_id: 'commute_details',
  block_header: 'Commute Details',
  block_description: 'Tell us about your daily commute!',
  enabled: true,
  required: true,
  questions: [
    {
      id: 'addr_home_street',
      question_header: 'Home Address',
      question_desc: 'Enter your street address',
      enabled: true,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: ['2656 Ellendale Pl'],
    },
    {
      id: 'addr_home_city',
      question_header: 'Home Address',
      question_desc: 'Enter your home city',
      enabled: true,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: ['Los Angeles'],
    },
    {
      id: 'addr_home_state',
      question_header: 'Home Address',
      question_desc: 'Enter your home state',
      enabled: true,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: ['CA'],
    },
    {
      id: 'addr_home_zip',
      question_header: 'Home Address',
      question_desc: 'Enter your home zip code',
      enabled: true,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: ['90007'],
    },
    {
      id: 'addr_work_street',
      question_header: 'Work Address',
      question_desc: 'Enter your street address',
      enabled: true,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: ['12125 Venice Blvd'],
    },
    {
      id: 'addr_work_city',
      question_header: 'Work Address',
      question_desc: 'Enter your work city',
      enabled: true,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: ['Los Angeles'],
    },
    {
      id: 'addr_work_state',
      question_header: 'Work Address',
      question_desc: 'Enter your work state',
      enabled: true,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: ['CA'],
    },
    {
      id: 'addr_work_zip',
      question_header: 'Work Address',
      question_desc: 'Enter your work zip code',
      enabled: true,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: ['90066'],
    },
  ],
};

module.exports = commute_details;
