const injection_details = {
  block_id: 'injection_details',
  block_header: 'Injection Details',
  enabled: false,
  required: false,
  questions: [
    {
      id: 'injections_occured',
      question_header: 'Injections',
      question_desc: 'Were there any injections after the case?',
      enabled: true,
      required: false,
      type: 'MC',
      options: [
        { value: 'Yes', children: ['injection_type'], blocks_enabled: [] },
        { value: 'No', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'injection_type',
      question_header: 'Injection Type',
      question_desc: 'Select the Injection Type',
      enabled: false,
      required: false,
      type: 'SATA',
      options: [
        { value: 'BMAC', children: ['BMAC_type'], blocks_enabled: [] },
        { value: 'PRP', children: ['PRP_type'], blocks_enabled: [] },
        { value: 'HA', children: ['HA_type'], blocks_enabled: [] },
        {
          value: 'Anesthetic',
          children: ['Anesthetic_inj_type'],
          blocks_enabled: [],
        },
        {
          value: 'Stem Cells',
          children: ['stem_cell_inj_type'],
          blocks_enabled: [],
        },
        {
          value: 'Cortisone',
          children: ['cortisone_inj_type'],
          blocks_enabled: [],
        },
        { value: 'Other', children: ['other_inj_type'], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'BMAC_type',
      question_header: 'BMAC',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'PRP_type',
      question_header: 'PRP',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'HA_type',
      question_header: 'HA',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'Anesthetic_inj_type',
      question_header: 'Anesthetic',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'stem_cell_inj_type',
      question_header: 'Stem Cells',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'cortisone_inj_type',
      question_header: 'Cortisone',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: 'other_inj_type',
      question_header: 'Other Injection',
      enabled: false,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: [],
    },
  ],
};

module.exports = injection_details;
