const injection_details = {
  block_id: 'injection_details',
  block_header: 'Injection Details',
  enabled: false,
  required: false,
  questions: [
    {
      id: '0',
      question_header: 'Injections',
      question_desc: 'Were there any injections after the case?',
      enabled: true,
      required: false,
      type: 'MC',
      options: [
        { value: 'Yes', children: ['1'], blocks_enabled: [] },
        { value: 'No', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '1',
      question_header: 'Injection Type',
      question_desc: 'Select the Injection Type',
      enabled: false,
      required: false,
      type: 'SATA',
      options: [
        { value: 'BMAC', children: ['2'], blocks_enabled: [] },
        { value: 'PRP', children: ['3'], blocks_enabled: [] },
        { value: 'HA', children: ['4'], blocks_enabled: [] },
        { value: 'Anesthetic', children: ['5'], blocks_enabled: [] },
        { value: 'Stem Cells', children: ['6'], blocks_enabled: [] },
        { value: 'Cortisone', children: ['8'], blocks_enabled: [] },
        { value: 'Other', children: ['7'], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '2',
      question_header: 'BMAC',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '3',
      question_header: 'PRP',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '4',
      question_header: 'HA',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '5',
      question_header: 'Anesthetic',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '6',
      question_header: 'Stem Cells',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '8',
      question_header: 'Cortisone',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        { value: 'Intra-articular', children: [], blocks_enabled: [] },
        { value: 'Extra-articular', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '7',
      question_header: 'Other Injection',
      enabled: false,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: [],
    },
  ],
};

module.exports = injection_details;
