const left_labrum =
  // left_labrum
  {
    block_id: 'left_labrum',
    block_header: 'Left Labrum Details',
    block_description: 'Details about the Left Labrum',
    enabled: false,
    required: true,
    questions: [
      {
        id: 'left_labrum_status',
        question_header: 'Left Labrum',
        question_desc: 'What was the status of the Left Labrum?',
        enabled: true,
        required: true,
        type: 'MC',
        options: [
          { value: 'Normal', children: [], blocks_enabled: [] },
          {
            value: 'Abnormal',
            children: [
              'left_labrum_labral_tear',
              'left_labrum_refixation',
              'left_labrum_other_abnormalities',
            ],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_refixation',
        question_header: 'Left Labrum',
        question_desc: 'Was this a takedown for refixation?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Yes', children: [], blocks_enabled: [] },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_labral_tear',
        question_header: 'Left Labral Tear',
        question_desc: 'Was there a Left Labral Tear?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: [
              'left_labrum_tear_clockface_from',
              'left_labrum_tear_clockface_to',
              'left_labrum_tear_treatment',
              'left_labrum_implant_manu_tear_type',
            ],
            blocks_enabled: [],
          },
          {
            value: 'No',
            children: [
              'left_labrum_other_clockface_from',
              'left_labrum_other_clockface_to',
              'left_labrum_other_ab_treatment',
            ],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_implant_manu_tear_type',
        question_header: 'Left Labral Tear',
        question_desc: 'What was the type of Labral Tear?',
        enabled: false,
        required: true,
        type: 'SATA',
        options: [
          { value: 'Flap', children: [], blocks_enabled: [] },
          { value: 'Fibrillated', children: [], blocks_enabled: [] },
          { value: 'Degenerative', children: [], blocks_enabled: [] },
          { value: 'Radial', children: [], blocks_enabled: [] },
          {
            value: 'Labral Chondral Separation',
            children: [],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_other_abnormalities',
        question_header: 'Other Labrum Abnormalities',
        question_desc: 'What other Labrum abnormalites were observed?',
        enabled: false,
        required: false,
        type: 'SATA',
        options: [
          {
            value: 'Hypertrophic',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Hypotrophic', children: [], blocks_enabled: [] },
          { value: 'Ossified', children: [], blocks_enabled: [] },
          { value: 'Calcific', children: [], blocks_enabled: [] },
          {
            value: 'Mucinoid (Yellow Discoloration)',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Bruised', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_labrum_other_ab_system'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_other_ab_system',
        question_header: 'Other Labrum Abnormalities',
        question_desc: 'What was the Other Labrum Abnormalities System?',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_tear_clockface_from',
        question_header:
          'Tear clockface "from" (anterior / medial most aspect)',
        long_question_desc: [
          'Use as referenced: ',
          "Anterior - 3 o'clock",
          "Lateral - 12 o'clock",
        ],
        enabled: false,
        required: true,
        type: 'DDS',
        options: [
          { value: '12', children: [], blocks_enabled: [] },
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
          { value: '11', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_tear_clockface_to',
        question_header: 'Tear clockface "to" (anterior / medial most aspect)',
        long_question_desc: [
          'Use as referenced: ',
          "Anterior - 3 o'clock",
          "Lateral - 12 o'clock",
        ],
        enabled: false,
        required: true,
        type: 'DDS',
        options: [
          { value: '12', children: [], blocks_enabled: [] },
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
          { value: '11', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_tear_treatment',
        question_header: 'Tear Treatment',
        question_desc: 'How was the tear treated?',
        enabled: false,
        required: true,
        type: 'SATA',
        options: [
          { value: 'Debridement', children: [], blocks_enabled: [] },
          { value: 'Labrectomy', children: [], blocks_enabled: [] },
          {
            value: 'Repair',
            children: [
              'left_labrum_implant_manu',
              'left_labrum_num_anc',
              'left_labrum_suture_config',
            ],
            blocks_enabled: [],
          },
          {
            value: 'Reconstruction',
            children: [
              'left_labrum_graft_type',
              'left_labrum_graft_length',
              'left_labrum_implant_manu',
              'left_labrum_num_anc',
            ],
            blocks_enabled: [],
          },
          {
            value: 'Augmentation',
            children: [
              'left_labrum_graft_type',
              'left_labrum_graft_length',
              'left_labrum_implant_manu',
              'left_labrum_num_anc',
            ],
            blocks_enabled: [],
          },
          { value: 'None', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_graft_type',
        question_header: 'Type of Labral Graft',
        question_desc: 'What was the type of Labral Graft?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'MC',
        options: [
          {
            value: 'Allograft',
            children: ['left_labrum_allograft_type'],
            blocks_enabled: [],
          },
          {
            value: 'Autograft',
            children: ['left_labrum_autograft_type'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_allograft_type',
        question_header: 'Allograft Graft Type',
        question_desc: 'What was the Graft Type?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'MC',
        options: [
          { value: 'IT Band', children: [], blocks_enabled: [] },
          { value: 'Hamstring', children: [], blocks_enabled: [] },
          { value: 'Posterior Tibialis', children: [], blocks_enabled: [] },
          { value: 'Anterior Tibialis', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_labrum_graft_type_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_autograft_type',
        question_header: 'Autograft Graft Type',
        question_desc: 'What was the Graft Type?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'MC',
        options: [
          { value: 'IT Band', children: [], blocks_enabled: [] },
          { value: 'Hamstring', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_labrum_graft_type_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_graft_type_other',
        question_header: 'Other Graft Type',
        question_desc: 'Enter Other Graft Type',
        enabled: false,
        required: true,
        isPref: true,
        type: 'FR',
        fr_type: 'text',
        value: [],
      },
      {
        id: 'left_labrum_graft_length',
        question_header: 'Length of Graft',
        question_desc: 'What was the length of the Graft in centimeters?',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'number',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_implant_manu',
        question_header: 'Implant Manufacturer',
        question_desc: 'Who manufactured the implant?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          {
            value: 'Arthex',
            children: ['left_labrum_arthex_system'],
            blocks_enabled: [],
          },
          {
            value: 'Biomet',
            children: ['left_labrum_biomet_system'],
            blocks_enabled: [],
          },
          {
            value: 'Conmed',
            children: ['left_labrum_conmed_system'],
            blocks_enabled: [],
          },
          {
            value: 'Smith & Nephew',
            children: ['left_labrum_smith_nephew'],
            blocks_enabled: [],
          },
          {
            value: 'Stryker / Pivot',
            children: ['left_labrum_stryker_pivot_type'],
            blocks_enabled: [],
          },
          {
            value: 'Medacta',
            children: ['left_labrum_medacta_system'],
            blocks_enabled: [],
          },
          {
            value: 'Other',
            children: [
              'left_labrum_implant_manu_other',
              'left_labrum_anchor_type',
              'left_labrum_anchor_mat',
            ],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_implant_manu_other',
        question_header: 'Other Implant Manufacturer',
        question_desc: 'What was the Other Implant Manufacturer?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_arthex_system',
        question_header: 'Arthex Implant System',
        question_desc: 'What was the Arthex Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          { value: 'Pushlock', children: [], blocks_enabled: [] },
          {
            value: 'Biocomposite Pushlock',
            children: [],
            blocks_enabled: [],
          },
          { value: 'PEEK SutureTak', children: [], blocks_enabled: [] },
          {
            value: 'Biocomposite SutureTak',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Knotless FiberTak', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_labrum_arthex_system_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_arthex_system_other',
        question_header: 'Other Arthex Implant System',
        question_desc: 'What was the Other Arthex Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_biomet_system',
        question_header: 'Biomet Implant System',
        question_desc: 'What was the Biomet Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          {
            value: 'Juggerknot Long Soft Anchor',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Other',
            children: ['left_labrum_biomet_system_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_biomet_system_other',
        question_header: 'Other Biomet Implant System',
        question_desc: 'What was the Other Biomet Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_conmed_system',
        question_header: 'Conmed Implant System',
        question_desc: 'What was the Conmed Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          {
            value: 'Poplok',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Press FT', children: [], blocks_enabled: [] },
          { value: 'Bio Mini Revo', children: [], blocks_enabled: [] },
          { value: 'Y Knot', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_labrum_conmed_system_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_conmed_system_other',
        question_header: 'Other Conmed Implant System',
        question_desc: 'What was the Other Conmed Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_smith_nephew',
        question_header: 'Smith & Nephew Implant System',
        question_desc: 'What was the Smith & Nephew Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          { value: 'Bioraptor Knotless', children: [], blocks_enabled: [] },
          { value: 'Bioraptor PK', children: [], blocks_enabled: [] },
          { value: 'Labralock P', children: [], blocks_enabled: [] },
          { value: 'Mini Magnum', children: [], blocks_enabled: [] },
          { value: 'Mini Magnum Plus', children: [], blocks_enabled: [] },
          { value: 'Osteoraptor', children: [], blocks_enabled: [] },
          { value: 'Q-Fix', children: [], blocks_enabled: [] },
          { value: 'Mini Q-Fix', children: [], blocks_enabled: [] },
          { value: 'Speedlock', children: [], blocks_enabled: [] },
          { value: 'Speedlock Plus', children: [], blocks_enabled: [] },
          { value: 'Speedlock Ultra', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_labrum_smith_nephew_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_smith_nephew_other',
        question_header: 'Other Smith & Nephew Implant System',
        question_desc: 'What was the Other Smith & Nephew Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_stryker_pivot_type',
        question_header: 'Stryker / Pivot Implant System',
        question_desc: 'What was the Stryker / Pivot Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          { value: 'Iconix', children: [], blocks_enabled: [] },
          { value: 'Pivot Cinchlock SS', children: [], blocks_enabled: [] },
          { value: 'Pivot Nanotak Flex', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_labrum_stryker_pivot_type_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_stryker_pivot_type_other',
        question_header: 'Other Stryker / Pivot Implant System',
        question_desc: 'What was the Other Stryker / Pivot Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_medacta_system',
        question_header: 'Medacta Implant System',
        question_desc: 'What was the Medacta Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          { value: 'Mectalock PPEK', children: [], blocks_enabled: [] },
          { value: 'Mectalock TI', children: [], blocks_enabled: [] },
          { value: 'Mectatap TI', children: [], blocks_enabled: [] },
          { value: 'Mectalock All Suture', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_labrum_medacta_system_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_labrum_medacta_system_other',
        question_header: 'Other Medacta Implant System',
        question_desc: 'What was the Other Medacta Implant System?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_labrum_num_anc',
        question_header: 'Number of Anchors',
        question_desc: 'How many anchors were used?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'DDS',
        options: [
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_anchor_mat',
        question_header: 'Anchor Material',
        question_desc: 'What was the material of the anchor?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          { value: 'All-suture Based', children: [], blocks_enabled: [] },
          { value: 'Metal', children: [], blocks_enabled: [] },
          { value: 'Bioabsorbable', children: [], blocks_enabled: [] },
          { value: 'PEEK', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_anchor_type',
        question_header: 'Anchor Type',
        question_desc: 'What type of anchor was used?',
        enabled: false,
        required: true,
        isPref: true,
        type: 'SATA',
        options: [
          { value: 'Knotted', children: [], blocks_enabled: [] },
          { value: 'Knotless', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_suture_config',
        question_header: 'Suture Configuration',
        question_desc: 'What was the suture configuration?',
        enabled: false,
        required: true,
        type: 'SATA',
        options: [
          { value: 'Simple / Cerclage', children: [], blocks_enabled: [] },
          {
            value: 'Mattress / Base Fixation',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Hybrid Combination', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_other_clockface_from',
        question_header:
          'Other clockface "from" (anterior / medial most aspect)',
        long_question_desc: [
          'Use as referenced: ',
          "Anterior - 3 o'clock",
          "Lateral - 12 o'clock",
        ],
        enabled: false,
        required: true,
        type: 'DDS',
        options: [
          { value: '12', children: [], blocks_enabled: [] },
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
          { value: '11', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_other_clockface_to',
        question_header: 'Other clockface "to" (anterior / medial most aspect)',
        long_question_desc: [
          'Use as referenced: ',
          "Anterior - 3 o'clock",
          "Lateral - 12 o'clock",
        ],
        enabled: false,
        required: true,
        type: 'DDS',
        options: [
          { value: '12', children: [], blocks_enabled: [] },
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
          { value: '11', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_labrum_other_ab_treatment',
        question_header: 'Other Abnormalitiy Treatment',
        question_desc: 'How was the tear treated?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'None', children: [], blocks_enabled: [] },
          {
            value: 'Debridement / Resection',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Repair',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Reconstruction',
            children: [],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
    ],
  };

module.exports = left_labrum;
