const left_femur =
  // left_femur
  {
    block_id: 'left_femur',
    block_header: 'Left Femur Details',
    block_description: 'Details about the Left Femur',
    enabled: false,
    required: true,
    questions: [
      {
        id: 'left_femur_status',
        question_header: 'Left Femur',
        question_desc: 'What was the status of the Left Femur?',
        enabled: true,
        required: true,
        type: 'MC',
        options: [
          { value: 'Normal', children: [], blocks_enabled: [] },
          {
            value: 'Abnormal',
            children: ['left_femur_cam_lesion', 'left_femur_cartilage_lesion'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_femur_cam_lesion',
        question_header: 'Cam Lesion',
        question_desc: 'Was there Cam Lesion present?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: [
              'left_femur_cam_lesion_treatment',
              'left_femur_cam_lesion_loc',
            ],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_femur_cam_lesion_loc',
        question_header: 'Cam Lesion',
        question_desc: 'Location of the Cam Lesion',
        enabled: false,
        required: true,
        type: 'SATA',
        options: [
          { value: 'Anteromedial', children: [], blocks_enabled: [] },
          { value: 'Anterior', children: [], blocks_enabled: [] },
          { value: 'Lateral', children: [], blocks_enabled: [] },
          { value: 'Anterolateral', children: [], blocks_enabled: [] },
          { value: 'Posterolateral', children: [], blocks_enabled: [] },
          { value: 'Posterior', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_femur_cam_lesion_treatment',
        question_header: 'Cam Lesion Treatment',
        question_desc: 'How was the Cam Lesion treated?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Osteoplasty', children: [], blocks_enabled: [] },
          { value: 'None', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_femur_cartilage_lesion',
        question_header: 'Femur Cartilage Lesion',
        question_desc: 'Was there Femur Cartilage Lesion present?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: [
              'left_femur_articular_cart_loc',
              'left_femur_cart_damage',
              'left_femur_cart_treatment',
            ],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_femur_articular_cart_loc',
        question_header: 'Articular Cartilage Location',
        question_desc: 'Select areas of GREATEST Articular Cartilage Damage',
        enabled: false,
        required: true,
        type: 'SATA',
        options: [
          { value: 'Central Head', children: [], blocks_enabled: [] },
          { value: 'Anterior', children: [], blocks_enabled: [] },
          { value: 'Posterior', children: [], blocks_enabled: [] },
          { value: 'Lateral', children: [], blocks_enabled: [] },
          { value: 'Medial', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_femur_cart_damage',
        question_header:
          'Select Classification for the degree of worst cartilage damage:',
        long_question_desc: [
          'Grade 0 - Normal',
          'Grade 1 - Softening',
          'Grade 2a - Cartilage lesion with < 50% depth',
          'Grade 2b - Cartilage lesion with > 50% depth',
          'Grade 3 - Exposed bone',
          'Grade 4 - Full thickness, Cartilage Loss & Bone Loss',
        ],
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Grade 0',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 1',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 2a',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 2b',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 3',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 4',
            children: [],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_femur_cart_treatment',
        question_header: 'Femoral Head Cartilage Treatment',
        question_desc: 'What was the Treatment for the Femoral Head Cartilage?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'None', children: [], blocks_enabled: [] },
          { value: 'Chondroplasty', children: [], blocks_enabled: [] },
          { value: 'Microfracture', children: [], blocks_enabled: [] },
          { value: 'Cartilage Scaffold', children: [], blocks_enabled: [] },
          {
            value: 'Juvenile Cartilage Cells',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Fibrin Glue', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_femur_cart_treatment_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'left_femur_cart_treatment_other',
        question_header: 'Other Femoral Head Cartilage Treatment',
        question_desc: 'What was the Other Femoral Head Cartilage Treatment?',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: 'left_femur_avn_treatment',
        question_header: 'AVN Treatment',
        question_desc: 'What was the Treatment for the AVN?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'K-wire / Steinman Pin Drilling',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Core Decompression', children: [], blocks_enabled: [] },
          { value: 'Bone Grafting', children: [], blocks_enabled: [] },
          { value: 'Stem Cell / PRP', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['left_femur_other_avn_treatment'],
            blocks_enabled: [],
          },
          { value: 'None', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'left_femur_other_avn_treatment',
        question_header: 'Other AVN Treatment',
        question_desc: 'What was the Other AVN Treatment?',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
    ],
  };

module.exports = left_femur;
