const other_right_details = {
  block_id: 'other_right_details',
  block_header: 'Additional Right Hip Details',
  enabled: false,
  required: true,
  questions: [
    {
      id: '0',
      question_header: 'Other Surgery Details',
      question_desc: 'Select all that apply',
      enabled: true,
      required: false,
      type: 'SATA',
      options: [
        { value: 'Ligamentum Teres', children: ['4'], blocks_enabled: [] },
        { value: 'Capsular Plication', children: ['6'], blocks_enabled: [] },
        {
          value: 'Iliopsoas Tendon Lengthening',
          children: ['1'],
          blocks_enabled: [],
        },
        {
          value: 'IT Band Lengthening (external snapping)',
          children: ['3'],
          blocks_enabled: [],
        },
        {
          value: 'Trochanteric Bursectomy',
          children: ['2'],
          blocks_enabled: [],
        },
        {
          value: 'Gluteus Tendon Repair',
          children: [],
          blocks_enabled: ['right_glute_repair'],
        },
        {
          value: 'I&D for Joint Infection',
          children: [],
          blocks_enabled: [],
        },
        { value: 'Subchondroplasty', children: ['5'], blocks_enabled: [] },
        { value: 'Hamstring Repair', children: [], blocks_enabled: [] },
        {
          value: 'Open Cartilage Repair',
          children: [],
          blocks_enabled: [],
        },
        {
          value: 'Proximal Femur Osteotomy (PFO)',
          children: [],
          blocks_enabled: [],
        },
        {
          value: 'Surgical Hip Dislocation (SDH)',
          children: [],
          blocks_enabled: [],
        },
        { value: 'ORIF', children: [], blocks_enabled: [] },
        { value: 'Other', children: ['8'], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '8',
      question_header: 'Other Right Details',
      question_desc: 'Enter any other details observed about the right side',
      enabled: false,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: [],
    },
    {
      id: '1',
      question_header: 'Iliopsoas Tendon Lengthening Details',
      question_desc: 'At What Level was the Iliopsoas Tendon Lengthened?',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        { value: 'Central Compartment', children: [], blocks_enabled: [] },
        {
          value: 'Peripheral Compartment',
          children: [],
          blocks_enabled: [],
        },
        { value: 'Lesser Trochanter', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '2',
      question_header: 'Trochanteric Bursectomy Details',
      enabled: false,
      required: true,
      type: 'MC',
      options: [
        { value: 'IT Band Sparing', children: [], blocks_enabled: [] },
        { value: 'Tenoplasty', children: [], blocks_enabled: [] },
      ],
      value: [],
    },
    {
      id: '3',
      question_header: 'IT Band Lengthening (external snapping) Details',
      question_desc: 'Select all that apply',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        {
          value: 'Posterior Band Incision',
          children: [],
          blocks_enabled: [],
        },
        {
          value: 'Central IT Band Partial Excision',
          children: [],
          blocks_enabled: [],
        },
      ],
      value: [],
    },
    {
      id: '4',
      question_header: 'Ligamentum Teres Details',
      question_desc: 'Select all that apply',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        {
          value: 'Debridement',
          children: [],
          blocks_enabled: [],
        },
        {
          value: 'Reconstruction',
          children: ['9'],
          blocks_enabled: [],
        },
      ],
      value: [],
    },
    {
      id: '5',
      question_header: 'Subchondroplasty Details',
      question_desc: 'Select all that apply',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        {
          value: 'Acetabulum',
          children: [],
          blocks_enabled: [],
        },
        {
          value: 'Femur',
          children: [],
          blocks_enabled: [],
        },
      ],
      value: [],
    },
    {
      id: '6',
      question_header: 'Plication Details',
      question_desc: 'Location of Plication',
      enabled: false,
      required: true,
      type: 'SATA',
      options: [
        {
          value: 'Iliofemoral Ligament',
          children: [],
          blocks_enabled: [],
        },
        {
          value: 'RICH',
          children: [],
          blocks_enabled: [],
        },
        {
          value: 'Other',
          children: ['7'],
          blocks_enabled: [],
        },
      ],
      value: [],
    },
    {
      id: '7',
      question_header: 'Other Plication Details',
      question_desc: 'Enter other details observed about the Plication',
      enabled: false,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: [],
    },
    {
      id: '9',
      question_header: 'Ligamentum Teres Reconstruction Graft Type',
      question_desc: 'Enter the Ligamentum Teres Reconstruction Graft Type',
      enabled: false,
      required: true,
      type: 'FR',
      fr_type: 'text',
      value: [],
    },
  ],
};

module.exports = other_right_details;
