const right_acetabulum =
  // right_acetabulum
  {
    block_id: 'right_acetabulum',
    block_header: 'Right Acetabulum Details',
    block_description: 'Details about the Bony Acetabulum',
    enabled: false,
    required: true,
    questions: [
      {
        id: 'right_acetabulum_status',
        question_header: 'Right Acetabulum',
        question_desc: 'What was the status of the Right Acetabulum?',
        enabled: true,
        required: true,
        type: 'MC',
        options: [
          { value: 'Normal', children: [], blocks_enabled: [] },
          {
            value: 'Abnormal',
            children: [
              'right_acetabulum_pincer_lesion',
              'right_acetabulum_os',
              'right_acetabulum_rim_stress',
              'right_acetabulum_post_rim',
            ],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'right_acetabulum_pincer_lesion',
        question_header: 'Pincer Lesion',
        question_desc: 'Was there a Pincer Lesion?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Yes', children: [], blocks_enabled: [] },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'right_acetabulum_os',
        question_header: 'Os Acetabuli',
        question_desc: 'Was there a Os Acetabuli?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: ['right_acetabulum_os_treatment'],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'right_acetabulum_os_treatment',
        question_header: 'Os Acetabuli Treatment',
        question_desc: 'What was the Treatment for the Os Acetabuli?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Internal Fixation', children: [], blocks_enabled: [] },
          { value: 'Removal', children: [], blocks_enabled: [] },
          { value: 'Leave Alone', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['right_acetabulum_os_treatment_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'right_acetabulum_os_treatment_other',
        question_header: 'Other Treatment',
        question_desc: 'Enter Treatment for Os Acetabuli',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        value: [],
      },
      {
        id: 'right_acetabulum_rim_stress',
        question_header: 'Rim Stress Fracture',
        question_desc: 'Was there a Rim Stress Fracture?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: ['right_acetabulum_rim_stress_treatment'],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'right_acetabulum_rim_stress_treatment',
        question_header: 'Rim Stress Fracture Treatment',
        question_desc: 'What was the Treatment for the Rim Stress Fracture?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Internal Fixation', children: [], blocks_enabled: [] },
          { value: 'Removal', children: [], blocks_enabled: [] },
          { value: 'Leave Alone', children: [], blocks_enabled: [] },
          {
            value: 'Other',
            children: ['right_acetabulum_rim_stress_treatment_other'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: 'right_acetabulum_rim_stress_treatment_other',
        question_header: 'Other Treatment',
        question_desc: 'Enter Treatment for Rim Stress Fracture',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        value: [],
      },
      {
        id: 'right_acetabulum_post_rim',
        question_header: 'Posterior Rim Fracture',
        question_desc: 'Was there an Acute Posterior Rim Fracture?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: ['right_acetabulum_post_rim_type'],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: 'right_acetabulum_post_rim_type',
        question_header: 'Posterior Rim Fracture',
        question_desc: 'What type of Fracture?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Displaced', children: [], blocks_enabled: [] },
          { value: 'Not Displaced', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
    ],
  };

module.exports = right_acetabulum;
