export const height_weight =
  // height_weight
  {
    block_id: 'height_weight',
    block_header: 'Patient Physical Details',
    block_description: 'Patient Measurements',
    enabled: true,
    required: true,
    questions: [
      {
        id: '3',
        question_header: "Was the patient's Height and Weight recorded?",
        enabled: true,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: ['4', '5', '6', '43', '44'],
            blocks_enabled: [],
          },
          {
            value: 'No',
            children: [],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: '4',
        question_header: 'Patient Height',
        question_desc: 'Height',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'number',
        children: [],
        value: [],
      },
      {
        id: '43',
        question_header: 'Height Unit',
        question_desc: 'What unit was used to measure height?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Inches', children: [], blocks_enabled: [] },
          { value: 'Centimeters', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '5',
        question_header: 'Patient Weight',
        question_desc: 'Weight in Pounds',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'number',
        children: [],
        value: [],
      },
      {
        id: '44',
        question_header: 'Weight Unit',
        question_desc: 'What unit was used to measure weight?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Pounds', children: [], blocks_enabled: [] },
          { value: 'Kilograms', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      // {
      //   id: '6',
      //   question_header: 'Patient BMI',
      //   question_desc: 'Body Mass Index',
      //   enabled: false,
      //   required: true,
      //   type: 'FR',
      //   fr_type: 'number',
      //   children: [],
      //   value: [],
      // },
    ],
  };
