export const left_femur =
  // left_femur
  {
    block_id: 'left_femur',
    block_header: 'Left Femur Details',
    block_description: 'Details about the Left Femur',
    enabled: false,
    required: true,
    questions: [
      {
        id: '0',
        question_header: 'Left Femur',
        question_desc: 'What was the status of the Left Femur?',
        enabled: true,
        required: true,
        type: 'MC',
        options: [
          { value: 'Normal', children: [], blocks_enabled: [] },
          {
            value: 'Abnormal',
            children: ['1', '2', '3'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: '1',
        question_header: 'Cam Lesion',
        question_desc: 'Was there Cam Lesion present?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: ['4', '5', '6', '7', 98],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '98',
        question_header: 'Cam Lesion',
        question_desc: 'Select all that apply',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Anteromedial', children: [], blocks_enabled: [] },
          { value: 'Anterior', children: [], blocks_enabled: [] },
          { value: 'Lateral', children: [], blocks_enabled: [] },
          { value: 'Posterolateral', children: [], blocks_enabled: [] },
          { value: 'Posterior', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '4',
        question_header: 'Cam Lesion clockface "from"',
        long_question_desc: ["Anterior - 3 o'clock", "Lateral - 12 o'clock"],
        enabled: false,
        required: true,
        type: 'DDS',
        options: [
          { value: '12', children: [], blocks_enabled: [] },
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
          { value: '11', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '5',
        question_header: 'Cam Lesion clockface "to"',
        long_question_desc: ["Anterior - 3 o'clock", "Lateral - 12 o'clock"],
        enabled: false,
        required: true,
        type: 'DDS',
        options: [
          { value: '12', children: [], blocks_enabled: [] },
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
          { value: '11', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '7',
        question_header: 'Cam Lesion Treatment',
        question_desc: 'How was the Cam Lesion treated?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Osteoplasty', children: [], blocks_enabled: [] },
          { value: 'None', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '2',
        question_header: 'Femur Cartilage Lesion',
        question_desc: 'Was there Femur Cartilage Lesion present?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: ['9', '10', '11'],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '9',
        question_header: 'Articular Cartilage Location',
        question_desc: 'Select areas of GREATEST Articular Cartilage Damage',
        enabled: false,
        required: true,
        type: 'SATA',
        options: [
          { value: 'Central Head', children: [], blocks_enabled: [] },
          { value: 'Anterior', children: [], blocks_enabled: [] },
          { value: 'Posterior', children: [], blocks_enabled: [] },
          { value: 'Lateral', children: [], blocks_enabled: [] },
          { value: 'Radial', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '10',
        question_header: 'Select Classification of area of greatest damage:',
        long_question_desc: [
          'Grade 0 - Normal',
          'Grade 1 - Softening',
          'Grade 2a - Cartilage lesion with < 50% depth',
          'Grade 2b - Cartilage lesion with > 50% depth',
          'Grade 3 - Exposed bone',
          'Grade 4 - Full thickness, Cartilage loss & bone loss',
        ],
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Grade 0',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 1',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 2a',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 2b',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 3',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Grade 4',
            children: [],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: '11',
        question_header: 'Articular Separation Treatment',
        question_desc: 'What was the Treatment for the Articular Separation?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'None', children: [], blocks_enabled: [] },
          { value: 'Chondroplasty', children: [], blocks_enabled: [] },
          { value: 'Microfracture', children: [], blocks_enabled: [] },
          { value: 'Cartilage Scaffold', children: [], blocks_enabled: [] },
          {
            value: 'Juvenile Cartilage Cells',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Fibrin Glue', children: [], blocks_enabled: [] },
          { value: 'Other', children: ['63'], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '63',
        question_header: 'Other Articular Separation Treatment',
        question_desc: 'What was the Other Articular Separation Treatment?',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: '3',
        question_header: 'AVN',
        question_desc: 'Was there AVN present?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Yes', children: ['13'], blocks_enabled: [] },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '13',
        question_header: 'AVN Treatment',
        question_desc: 'What was the Treatment for the AVN?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'K-wire / Steinman pin drilling',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Core decompression', children: [], blocks_enabled: [] },
          { value: 'Other', children: ['64'], blocks_enabled: [] },
          { value: 'None', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '64',
        question_header: 'Other AVN Treatment',
        question_desc: 'What was the Other AVN Treatment?',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
    ],
  };
