export const left_femur =
  // left_femur
  {
    block_id: 'left_femur',
    block_header: 'Left Femur Details',
    block_description: 'Details about the Left Femur',
    enabled: false,
    required: true,
    questions: [
      {
        id: '0',
        question_header: 'Left Acetabulum Articular Cartilage',
        question_desc:
          'What was the status of the Left Acetabulum Articular Cartilage?',
        enabled: true,
        required: true,
        type: 'MC',
        options: [
          { value: 'Normal', children: [], blocks_enabled: [] },
          {
            value: 'Abnormal',
            children: ['1', '2', '3'],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: '1',
        question_header: 'Cam Lesion',
        question_desc: 'Was there Cam Lesion present?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: ['4', '5', '6', '7'],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '4',
        question_header: 'Cam Lesion clockface "from"',
        question_desc: 'Enter starting clockface tear',
        enabled: false,
        required: true,
        type: 'DDS',
        options: [
          { value: '12', children: [], blocks_enabled: [] },
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
          { value: '11', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '5',
        question_header: 'Cam Lesion clockface "to"',
        question_desc: 'Enter ending clockface tear',
        enabled: false,
        required: true,
        type: 'DDS',
        options: [
          { value: '12', children: [], blocks_enabled: [] },
          { value: '1', children: [], blocks_enabled: [] },
          { value: '2', children: [], blocks_enabled: [] },
          { value: '3', children: [], blocks_enabled: [] },
          { value: '4', children: [], blocks_enabled: [] },
          { value: '5', children: [], blocks_enabled: [] },
          { value: '6', children: [], blocks_enabled: [] },
          { value: '7', children: [], blocks_enabled: [] },
          { value: '8', children: [], blocks_enabled: [] },
          { value: '9', children: [], blocks_enabled: [] },
          { value: '10', children: [], blocks_enabled: [] },
          { value: '11', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '6',
        question_header: 'Cam Lesion length',
        question_desc: 'Enter length, from proximal to distal (cm)',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: '0 - 4', children: [], blocks_enabled: [] },
          { value: '5 - 9', children: [], blocks_enabled: [] },
          { value: '10 - 14', children: [], blocks_enabled: [] },
          { value: '15 - 19', children: [], blocks_enabled: [] },
          { value: '20 - 24', children: [], blocks_enabled: [] },
          { value: '25 - 29', children: [], blocks_enabled: [] },
          { value: '30 - 34', children: [], blocks_enabled: [] },
          { value: '35 - 40', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '7',
        question_header: 'Tear Treatment',
        question_desc: 'How was the Cam Lesion treated?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Osteoplasty', children: [], blocks_enabled: [] },
          { value: 'None', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '2',
        question_header: 'Femur Cartilage Lesion',
        question_desc: 'Was there Femur Cartilage Lesion present?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Yes',
            children: ['9', '10', '11'],
            blocks_enabled: [],
          },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '9',
        question_header: 'Articular Cartilage Location',
        question_desc: 'Select areas of GREATEST Articular Cartilage Damage',
        enabled: false,
        required: true,
        type: 'SATA',
        img:
          'https://redcap.stanford.edu/surveys/index.php?pid=21691&__passthru=DataEntry%2Fimage_view.php&doc_id_hash=8b0e9330e9f70fbb9d7c05edaa0923c709e054c5&id=1165310&instance=1&s=3YFJPJAHNE',
        options: [
          { value: 'A Front', children: [], blocks_enabled: [] },
          { value: 'C Front', children: [], blocks_enabled: [] },
          { value: 'D Front', children: [], blocks_enabled: [] },
          { value: 'E Front', children: [], blocks_enabled: [] },
          { value: 'A Above', children: [], blocks_enabled: [] },
          { value: 'B Above', children: [], blocks_enabled: [] },
          { value: 'C Above', children: [], blocks_enabled: [] },
          { value: 'D Above', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '10',
        question_header: 'Select Beck Classification:',
        long_question_desc: [
          'Normal - Macroscopically sound cartilage',
          'Malacia - Roughening of surface, fibrillation',
          'Debonding - Loss of fixation to the subchronial bone, macroscopically sound cartialge, carpet phenomenon',
          'Cleavage - Loss of fixation to the suchronial bone, frayed edges, thinning of cartilage',
          'Defect - Full thickness defect',
        ],
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Normal',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Malacia',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Debonding',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Cleavage',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Defect',
            children: [],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: '11',
        question_header: 'Articular Separation Treatment',
        question_desc: 'What was the Treatment for the Articular Separation?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'None', children: [], blocks_enabled: [] },
          { value: 'Chondroplasty', children: [], blocks_enabled: [] },
          { value: 'Microfracture', children: [], blocks_enabled: [] },
          { value: 'Cartilage Scaffold', children: [], blocks_enabled: [] },
          {
            value: 'Juvenile Cartilage Cells',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Fibrin Glue', children: [], blocks_enabled: [] },
          { value: 'Other', children: ['63'], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '63',
        question_header: 'Other Articular Separation Treatment',
        question_desc: 'What was the Other Articular Separation Treatment?',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
      {
        id: '3',
        question_header: 'AVN',
        question_desc: 'Was there AVN present?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          { value: 'Yes', children: ['12', '13'], blocks_enabled: [] },
          { value: 'No', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '12',
        question_header: 'Steinberg Classification',
        question_desc: 'What is the Steinberg Classification?',
        long_question_desc: [
          'Stage 0 - normal or nondiagnostic radiographs, bone scan, and/or MRI',
          'Stage I - normal radiograph; abnormal bone scan/MRI',
          'Stage II - abnormal radiograph; abnormal bone scan/MRI',
          'Stage III - subchondral collapse, crescent sign, without flattening',
          'Stage IV - flattening of femoral head',
          'Stage V - joint space narrowing and/or acetabular changes',
          'Stage VI - advanced degenerative changes',
        ],
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'Stage 0',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Stage I',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Stage II',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Stage III',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Stage IV',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Stage V',
            children: [],
            blocks_enabled: [],
          },
          {
            value: 'Stage VI',
            children: [],
            blocks_enabled: [],
          },
        ],
        value: [],
      },
      {
        id: '13',
        question_header: 'AVN Treatment',
        question_desc: 'What was the Treatment for the AVN?',
        enabled: false,
        required: true,
        type: 'MC',
        options: [
          {
            value: 'K-sire / Steinman pin drilling',
            children: [],
            blocks_enabled: [],
          },
          { value: 'Core decompression', children: [], blocks_enabled: [] },
          { value: 'Other', children: ['64'], blocks_enabled: [] },
          { value: 'None', children: [], blocks_enabled: [] },
        ],
        value: [],
      },
      {
        id: '64',
        question_header: 'Other AVN Treatment',
        question_desc: 'What was the Other AVN Treatment?',
        enabled: false,
        required: true,
        type: 'FR',
        fr_type: 'text',
        options: [],
        value: [],
      },
    ],
  };
