export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SELECTED_OPTION = 'SELECT_OPTION';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREV_QUESTION = 'PREV_QUESTION';

export const NEW_NEXT_QUESTION = 'NEW_NEXT_QUESTION';
export const NEW_SELECT_OPTION = 'NEW_SELECT_OPTION';
export const MFRO_SELECT = 'MFRO_SELECT';
export const NEW_PREVIOUS_QUESTION = 'NEW_PREVIOUS_QUESTION';
