export const questionBank = [
  {
    id: '0',
    type: 'SATA',
    header: 'Question 0',
    text: 'question 0 text',
    value: ['option 2'],
    required: true,
    options: [
      { value: 'option 1' },
      { value: 'option 2' },
      { value: 'option 3' },
    ],
    dependents: [
      {
        value: 'option 1',
        children: ['1', '2'],
      },
      {
        value: 'option 2',
        children: ['2'],
      },
    ],
  },
  {
    id: '1',
    type: 'MC',
    header: 'Question 1',
    text: 'question 1 text',
    value: [],
    required: true,
    options: [
      { value: 'option 1' },
      { value: 'option 2' },
      { value: 'option 3' },
    ],
    dependents: [
      {
        value: 'option 2',
        children: ['2'],
      },
    ],
  },
  {
    id: '2',
    type: 'MC',
    header: 'Question 2',
    text: 'question 2 text',
    value: [],
    required: true,
    options: [
      { value: 'option 1' },
      { value: 'option 2' },
      { value: 'option 3' },
    ],
    dependents: [],
  },
  {
    id: '3',
    type: 'MFR',
    header: 'Question 3',
    text: 'question 3 text',
    value: [],
    required: true,
    options: [
      { value: 'option 1', q_id: '6' },
      { value: 'option 2', q_id: '7' },
    ],
    dependents: [],
  },
  {
    id: '4',
    type: 'FR',
    header: 'Question 4',
    text: 'this is an fr question',
    value: [],
    required: true,
    options: [],
    dependents: [],
  },
  {
    id: '5',
    type: 'MC',
    header: 'Question 5',
    text: 'question 5 text',
    value: [],
    required: true,
    options: [
      { value: 'option 1' },
      { value: 'option 2' },
      { value: 'option 3' },
      { value: 'option 4' },
      { value: 'option 5' },
    ],
    dependents: [],
  },
  {
    id: '6',
    type: 'MFRO',
    header: 'Question 6',
    text: 'question 6 text',
    value: [],
    required: true,
    options: [
      { value: 'option 1' },
      { value: 'option 2' },
      { value: 'option 3' },
    ],
    dependents: [],
  },
  {
    id: '7',
    type: 'MFRFR',
    header: 'Question 7',
    required: false,
    value: [],
    options: [],
    dependents: [],
  },
];
