export const realState = {
  ping: true,
  current: 'basic_details',
  blocks: [
    // basic_details
    {
      block_id: 'basic_details',
      block_header: 'Surgery Details',
      block_description: 'Surgery Date & Site',
      enabled: true,
      required: true,
      questions: [
        {
          id: '0',
          question_header: 'Date of Surgery',
          question_desc: "Defaulted to Today's Date",
          enabled: true,
          required: false,
          type: 'FR',
          fr_type: 'date',
          children: [],
          value: [],
        },
        {
          id: '1',
          question_header: 'Surgery Site',
          question_desc: 'Which side was operated on? Select all that apply',
          enabled: true,
          required: true,
          type: 'SATA',
          options: [
            {
              value: 'Left',
              children: [],
              blocks_enabled: ['left_details'],
            },
            {
              value: 'Right',
              children: [],
              blocks_enabled: ['right_details'],
            },
          ],
          value: [],
        },
        {
          id: '2',
          question_header: 'What level of data do you wish to report?',
          question_desc: 'Level 2 is detailed: includes alpha angle, tennis ',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Level 1',
              children: [],
              blocks_enabled: ['level_one_aap'],
            },
            {
              value: 'Level 2',
              children: [],
              blocks_enabled: [
                /* all blocks enabled by level 2 */
                'level_two_history_left',
                'level_two_history_right',
                'exam_under_anesthesia',
                'angle_details',
                'level_two_aap',
              ],
            },
          ],
          value: [],
        },
      ],
    },
    // height_weight
    {
      block_id: 'height_weight',
      block_header: 'Patient Physical Details',
      block_description: 'Patient Measurements',
      enabled: true,
      required: true,
      questions: [
        {
          id: '3',
          question_header: "Was the patient's Height and Weight recorded?",
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: ['4', '5', '6', '43', '44'],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '4',
          question_header: 'Patient Height',
          question_desc: 'Height',
          enabled: false,
          required: true,
          type: 'FR',
          fr_type: 'number',
          children: [],
          value: [],
        },
        {
          id: '43',
          question_header: 'Height Unit',
          question_desc: 'What unit was used to measure height?',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            { value: 'Inches', children: [], blocks_enabled: [] },
            { value: 'Centimeters', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '5',
          question_header: 'Patient Weight',
          question_desc: 'Weight in Pounds',
          enabled: false,
          required: true,
          type: 'FR',
          fr_type: 'number',
          children: [],
          value: [],
        },
        {
          id: '44',
          question_header: 'Weight Unit',
          question_desc: 'What unit was used to measure weight?',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            { value: 'Pounds', children: [], blocks_enabled: [] },
            { value: 'Kilograms', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '6',
          question_header: 'Patient BMI',
          question_desc: 'Body Mass Index',
          enabled: false,
          required: true,
          type: 'FR',
          fr_type: 'number',
          children: [],
          value: [],
        },
      ],
    },
    // prior_left
    {
      block_id: 'prior_left',
      block_header: 'Prior Surgical History: Left Hip',
      block_description: "Details of Patient's prior surgery on the left hip",
      enabled: true,
      required: true,
      questions: [
        {
          id: '24',
          question_header: 'Prior Surgical History: Left Hip',
          question_desc: 'Was surgery previously performed on the left hip',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: ['7', '8', '9'],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '7',
          question_header: 'Left Hip Surgery Type',
          question_desc: 'Select Surgery Type',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Arthrosocpy',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'THA',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'PAO',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'I&D',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'Surgical Dislocation',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'SCFE',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'Other',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '8',
          question_header: 'Multiple Prior Left Hip Surgeries',
          question_desc: 'Were there multiple surgeries performed?',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '9',
          question_header: 'All Prior Left Hip Surgeries',
          question_desc: 'Select all prior surgeries',
          enabled: false,
          required: false,
          type: 'SATA',
          options: [
            {
              value: 'Arthrosocpy',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'THA',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'PAO',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'I&D',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'Surgical Dislocation',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'SCFE',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'Other',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
      ],
    },
    // prior_right
    {
      block_id: 'prior_right',
      block_header: 'Prior Surgical History: Right Hip',
      block_description:
        "This is the question block description. It is not very long and probably won't take up many different lines",
      enabled: true,
      required: true,
      questions: [
        {
          id: '23',
          question_header: 'Prior Surgical History: Right Hip',
          question_desc: "Select Yes to add the patient's surgical History",
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: ['10', '11', '12'],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '10',
          question_header: 'Most Recent RIGHT Hip Surgery',
          question_desc: 'Select one',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Arthrosocpy',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'THA',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'PAO',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'I&D',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'Surgical Dislocation',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'SCFE',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'Other',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '11',
          question_header: 'Multiple Prior RIGHT Hip Surgeries?',
          question_desc: '',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '12',
          question_header: 'All Prior RIGHT Hip Surgeries',
          question_desc: 'Select all that apply',
          enabled: false,
          required: false,
          type: 'SATA',
          options: [
            {
              value: 'Arthrosocpy',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'THA',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'PAO',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'I&D',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'Surgical Dislocation',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'SCFE',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'Other',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
      ],
    },
    // level_two_history_left
    {
      block_id: 'level_two_history_left',
      block_header: 'Injury History - Left',
      block_description:
        "This is the question block description. It is not very long and probably won't take up many different lines",
      enabled: false,
      required: true,
      questions: [
        {
          id: '13',
          question_header: 'History of DVT',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '14',
          question_header: 'History of Joint Infection',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '15',
          question_header: 'History of Perthes',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '16',
          question_header: 'History of DDH',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '17',
          question_header: 'History of SCFE',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
      ],
    },
    // level_two_history_right
    {
      block_id: 'level_two_history_right',
      block_header: 'Injury History - Right',
      block_description:
        "This is the question block description. It is not very long and probably won't take up many different lines",
      enabled: false,
      required: true,
      questions: [
        {
          id: '18',
          question_header: 'History of DVT',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '19',
          question_header: 'History of Joint Infection',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '20',
          question_header: 'History of Perthes',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '21',
          question_header: 'History of DDH',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
        {
          id: '22',
          question_header: 'History of SCFE',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            {
              value: 'Yes',
              children: [],
              blocks_enabled: [],
            },
            {
              value: 'No',
              children: [],
              blocks_enabled: [],
            },
          ],
          value: [],
        },
      ],
    },
    // exam_under_anesthesia
    {
      block_id: 'exam_under_anesthesia',
      block_header: 'Exam Under Anesthesia',
      block_description:
        'Details about the Exam while the patient was under anesthesia',
      enabled: false,
      required: true,
      questions: [
        {
          id: '25',
          question_header: 'Left PROM Performed',
          question_desc: 'Was PROM performed on the left side?',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Yes', children: ['26', '27', '28'], blocks_enabled: [] },
            { value: 'No', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '26',
          question_header: 'Left PROM: FF',
          question_desc: 'Enter range',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            { value: '180', children: [], blocks_enabled: [] },
            { value: '150 to 179', children: [], blocks_enabled: [] },
            { value: '120 to 149', children: [], blocks_enabled: [] },
            { value: '90 to 119', children: [], blocks_enabled: [] },
            { value: '60 to 89', children: [], blocks_enabled: [] },
            { value: '30 to 59', children: [], blocks_enabled: [] },
            { value: '0 to 29', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '27',
          question_header: 'Left PROM in 90 deg: IR',
          question_desc: 'Enter range',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            { value: '90', children: [], blocks_enabled: [] },
            { value: '75 to 89', children: [], blocks_enabled: [] },
            { value: '60 to 74', children: [], blocks_enabled: [] },
            { value: '45 to 59', children: [], blocks_enabled: [] },
            { value: '30 to 44', children: [], blocks_enabled: [] },
            { value: '15 to 29', children: [], blocks_enabled: [] },
            { value: '0 to 14', children: [], blocks_enabled: [] },
            { value: '-1 to -14', children: [], blocks_enabled: [] },
            { value: '-15 to -29', children: [], blocks_enabled: [] },
            { value: '-30 to -44', children: [], blocks_enabled: [] },
            { value: '-45', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '28',
          question_header: 'Left PROM in 90 deg: ER',
          question_desc: 'Enter range',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            { value: '120', children: [], blocks_enabled: [] },
            { value: '105 to 119', children: [], blocks_enabled: [] },
            { value: '90 to 104', children: [], blocks_enabled: [] },
            { value: '75 to 89', children: [], blocks_enabled: [] },
            { value: '60 to 74', children: [], blocks_enabled: [] },
            { value: '45 to 59', children: [], blocks_enabled: [] },
            { value: '30 to 44', children: [], blocks_enabled: [] },
            { value: '15 to 29', children: [], blocks_enabled: [] },
            { value: '0 to 14', children: [], blocks_enabled: [] },
            { value: '-1 to -14', children: [], blocks_enabled: [] },
            { value: '-15 to -29', children: [], blocks_enabled: [] },
            { value: '-30 to -44', children: [], blocks_enabled: [] },
            { value: '-45', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '29',
          question_header: 'Right PROM Performed',
          question_desc: 'Was PROM performed on the right side?',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Yes', children: ['30', '31', '32'], blocks_enabled: [] },
            { value: 'No', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '30',
          question_header: 'Right PROM: FF',
          question_desc: 'Enter range',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            { value: '180', children: [], blocks_enabled: [] },
            { value: '150 to 179', children: [], blocks_enabled: [] },
            { value: '120 to 149', children: [], blocks_enabled: [] },
            { value: '90 to 119', children: [], blocks_enabled: [] },
            { value: '60 to 89', children: [], blocks_enabled: [] },
            { value: '30 to 59', children: [], blocks_enabled: [] },
            { value: '0 to 29', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '31',
          question_header: 'Right PROM in 90 deg: IR',
          question_desc: 'Enter range',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            { value: '90', children: [], blocks_enabled: [] },
            { value: '75 to 89', children: [], blocks_enabled: [] },
            { value: '60 to 74', children: [], blocks_enabled: [] },
            { value: '45 to 59', children: [], blocks_enabled: [] },
            { value: '30 to 44', children: [], blocks_enabled: [] },
            { value: '15 to 29', children: [], blocks_enabled: [] },
            { value: '0 to 14', children: [], blocks_enabled: [] },
            { value: '-1 to -14', children: [], blocks_enabled: [] },
            { value: '-15 to -29', children: [], blocks_enabled: [] },
            { value: '-30 to -44', children: [], blocks_enabled: [] },
            { value: '-45', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '32',
          question_header: 'Right PROM in 90 deg: ER',
          question_desc: 'Enter range',
          enabled: false,
          required: true,
          type: 'MC',
          options: [
            { value: '120', children: [], blocks_enabled: [] },
            { value: '105 to 119', children: [], blocks_enabled: [] },
            { value: '90 to 104', children: [], blocks_enabled: [] },
            { value: '75 to 89', children: [], blocks_enabled: [] },
            { value: '60 to 74', children: [], blocks_enabled: [] },
            { value: '45 to 59', children: [], blocks_enabled: [] },
            { value: '30 to 44', children: [], blocks_enabled: [] },
            { value: '15 to 29', children: [], blocks_enabled: [] },
            { value: '0 to 14', children: [], blocks_enabled: [] },
            { value: '-1 to -14', children: [], blocks_enabled: [] },
            { value: '-15 to -29', children: [], blocks_enabled: [] },
            { value: '-30 to -44', children: [], blocks_enabled: [] },
            { value: '-45', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
      ],
    },
    // angle_details
    {
      block_id: 'angle_details',
      block_header: 'Hip Angle Details',
      block_description: 'Details about the Angle of the Hip',
      enabled: false,
      required: true,
      questions: [
        {
          id: '33',
          question_header: 'Left Center Edge Angle',
          question_desc: 'Enter the Left Center Edge Angle',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '34',
          question_header: 'Left Center Edge Angle',
          question_desc: 'Enter the type of edge angle',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Sourcil', children: [], blocks_enabled: [] },
            { value: 'Edge', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '35',
          question_header: 'Left Alpha Angle',
          question_desc: 'Enter Left Side Alpha Angle',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '36',
          question_header: 'Left Femoral Version',
          question_desc: 'Enter the Left Femoral Version',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '37',
          question_header: 'Left Femoral Version',
          question_desc: 'Enter the type Left Femoral Version',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'CT', children: [], blocks_enabled: [] },
            { value: 'MRI', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '38',
          question_header: 'Left Tonnis Angle',
          question_desc: 'Enter the Left Tonnis Angle',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '39',
          question_header: 'Left Acetabular Index',
          question_desc: 'Enter the Left Acetabular Index',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '40',
          question_header: 'Right Center Edge Angle',
          question_desc: 'Enter the Right Center Edge Angle',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '41',
          question_header: 'Right Center Edge Angle',
          question_desc: 'Enter the type of edge angle',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Sourcil', children: [], blocks_enabled: [] },
            { value: 'Edge', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '42',
          question_header: 'Right Alpha Angle',
          question_desc: 'Enter Right Side Alpha Angle',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '43',
          question_header: 'Right Femoral Version',
          question_desc: 'Enter the Right Femoral Version',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '44',
          question_header: 'Right Femoral Version',
          question_desc: 'Enter the type Right Femoral Version',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'CT', children: [], blocks_enabled: [] },
            { value: 'MRI', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '45',
          question_header: 'Right Tonnis Angle',
          question_desc: 'Enter the Right Tonnis Angle',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '46',
          question_header: 'Right Acetabular Index',
          question_desc: 'Enter the Right Acetabular Index',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
      ],
    },
    // level_one_aap
    {
      block_id: 'level_one_aap',
      block_header: 'Approach, Anesthesia & Paraylsis Details',
      block_description:
        'Details about the Approach, Anesthesia & Paraylsis Details',
      enabled: false,
      required: true,
      questions: [
        {
          id: '46',
          question_header: 'Approach',
          question_desc: 'Enter the type of Approach',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Arthroscopy', children: [], blocks_enabled: [] },
            { value: 'Combined', children: [], blocks_enabled: [] },
            { value: 'Open', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '47',
          question_header: 'Anesthesia',
          question_desc: 'Enter the type of Anesthesia',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'General', children: [], blocks_enabled: [] },
            { value: 'Spinal', children: [], blocks_enabled: [] },
            { value: 'Lumbar Plexus Block', children: [], blocks_enabled: [] },
            { value: 'Spinal / Epidural', children: [], blocks_enabled: [] },
            { value: 'Other', children: ['48'], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '48',
          question_header: 'Anesthesia',
          question_desc: 'Enter Anesthesia type that was not listed above',
          enabled: false,
          required: true,
          type: 'FR',
          fr_type: 'text',
          value: [],
        },
        {
          id: '49',
          question_header: 'Paralysis',
          question_desc: 'Was there any paralysis?',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Yes', children: [], blocks_enabled: [] },
            { value: 'No', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
      ],
    },
    // level_two_aap
    {
      block_id: 'level_two_aap',
      block_header: 'Approach, Anesthesia & Paraylsis Details',
      block_description:
        'Details about the Approach, Anesthesia & Paraylsis Details',
      enabled: false,
      required: true,
      questions: [
        {
          id: '50',
          question_header: 'Approach',
          question_desc: 'Enter the type of Approach',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Arthroscopy', children: [], blocks_enabled: [] },
            { value: 'Combined', children: [], blocks_enabled: [] },
            { value: 'Open', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '51',
          question_header: 'Fluoroscopy Time',
          question_desc: 'Enter the Fluoroscopy Time',
          enabled: true,
          required: false,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '52',
          question_header: 'Operation Time',
          question_desc: 'Enter the Operation Time',
          enabled: true,
          required: true,
          type: 'FR',
          fr_type: 'number',
          value: [],
        },
        {
          id: '53',
          question_header: 'Traction Time',
          question_desc: 'Enter the Traction Time',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Less than 30 min', children: [], blocks_enabled: [] },
            { value: '31 - 60 min', children: [], blocks_enabled: [] },
            { value: '61 - 90 min', children: [], blocks_enabled: [] },
            { value: '91 - 120 min', children: [], blocks_enabled: [] },
            { value: '121 - 150 min', children: [], blocks_enabled: [] },
            { value: 'More than 150 min', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '54',
          question_header: 'Anesthesia',
          question_desc: 'Enter the type of Anesthesia',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'General', children: [], blocks_enabled: [] },
            { value: 'Spinal', children: [], blocks_enabled: [] },
            { value: 'Lumbar Plexus Block', children: [], blocks_enabled: [] },
            { value: 'Spinal / Epidural', children: [], blocks_enabled: [] },
            { value: 'Other', children: ['55'], blocks_enabled: [] },
          ],
          value: [],
        },
        {
          id: '55',
          question_header: 'Anesthesia',
          question_desc: 'Enter Anesthesia type that was not listed above',
          enabled: false,
          required: true,
          type: 'FR',
          fr_type: 'text',
          value: [],
        },
        {
          id: '56',
          question_header: 'Paralysis',
          question_desc: 'Was there any paralysis?',
          enabled: true,
          required: true,
          type: 'MC',
          options: [
            { value: 'Yes', children: [], blocks_enabled: [] },
            { value: 'No', children: [], blocks_enabled: [] },
          ],
          value: [],
        },
      ],
    },
    // left_details
    {
      block_id: 'left_details',
      block_header: 'Left Details',
      block_description:
        "This is the question block description. It is not very long and probably won't take up many different lines",
      enabled: false,
      required: true,
      questions: [
        {
          id: '8',
          question_header: 'Question seven is enabled',
          enabled: false,
          type: 'FR',
          options: [],
          value: [],
        },
      ],
    },
    // right_details
    {
      block_id: 'right_details',
      block_header: 'Right Details',
      block_description:
        "This is the question block description. It is not very long and probably won't take up many different lines",
      enabled: false,
      required: true,
      questions: [
        {
          id: '8',
          question_header: 'Question seven is enabled',
          enabled: false,
          type: 'FR',
          options: [],
          value: [],
        },
      ],
    },
  ],
};
