export const real_order = [
  {
    q_id: '0',
    value: [],
    enabled: true,
  },
  {
    q_id: '1',
    value: [],
    enabled: false,
  },
  {
    q_id: '2',
    value: [],
    enabled: false,
  },
  {
    q_id: '3',
    value: [],
    enabled: false,
  },
  {
    q_id: '4',
    value: [],
    enabled: false,
  },
  {
    q_id: '5',
    value: [],
    enabled: true,
  },
  {
    q_id: '6',
    value: [],
    enabled: false,
  },
  {
    q_id: '7',
    value: [],
    enabled: false,
  },
  {
    q_id: '8',
    value: [],
    enabled: false,
  },
  {
    q_id: '9',
    value: [],
    enabled: false,
  },
  {
    q_id: 'dummyQ',
    value: [],
    enabled: true,
  },
];

export const real_bank = [
  {
    id: '0',
    type: 'MC',
    header: 'Patient Demographics',
    text: "Was the Patient's Height/Weight recorded?",
    value: [],
    required: true,
    options: [{ value: 'Yes' }, { value: 'No' }],
    dependents: [
      {
        value: 'Yes',
        children: ['1'],
      },
    ],
  },
  {
    id: '1',
    type: 'MFR',
    header: 'Patient Demographics',
    text: 'Enter Patient Demographics',
    value: [],
    required: true,
    options: [
      { value: 'height', q_id: '2' },
      { value: 'weight', q_id: '3' },
      { value: 'bmi', q_id: '4' },
    ],
    dependents: [],
  },
  {
    id: '2',
    type: 'MFRFR',
    header: 'Patient Height (in)',
    required: true,
    value: [],
    options: [],
    dependents: [],
  },
  {
    id: '3',
    type: 'MFRFR',
    header: 'Patient Weight (lbs)',
    required: true,
    value: [],
    options: [],
    dependents: [],
  },
  {
    id: '4',
    type: 'MFRFR',
    header: 'Patient BMI',
    required: true,
    value: [],
    options: [],
    dependents: [],
  },
  {
    id: '5',
    type: 'MC',
    header: 'Prior Surgical History',
    text: 'Left Hip?',
    value: [],
    required: true,
    options: [{ value: 'Yes' }, { value: 'No' }],
    dependents: [
      {
        value: 'Yes',
        children: ['6'],
      },
    ],
  },
  {
    id: '6',
    type: 'MFR',
    header: 'Prior Surgical History',
    text: 'Enter Prior Surgury: Left Hip',
    value: [],
    required: true,
    options: [
      { value: 'Most recent Left Hip Surgery', q_id: '7' },
      { value: 'Multiple Prior Left Hip Surgeries', q_id: '8' },
      { value: 'All Prior Left hip Surgeries', q_id: '9' },
    ],
    dependents: [],
  },
  {
    id: '7',
    type: 'MFRO',
    header: 'Most recent Left Hip Surgery',
    value: [],
    required: true,
    options: [
      { value: 'Arthrosocpy' },
      { value: 'THA' },
      { value: 'PAO' },
      { value: 'I&D' },
      { value: 'Surgical Dislocation' },
      { value: 'SCFE' },
      { value: 'Other' },
    ],
    dependents: [],
  },
  {
    id: '8',
    type: 'MFRO',
    header: 'Multiple Prior Left Hip Surgeries',
    value: [],
    required: true,
    options: [{ value: 'Yes' }, { value: 'No' }],
    dependents: [],
  },
  {
    id: '9',
    type: 'MFRSATA',
    header: 'All Prior Left hip Surgeries',
    value: [],
    required: false,
    options: [
      { value: 'Arthrosocpy' },
      { value: 'THA' },
      { value: 'PAO' },
      { value: 'I&D' },
      { value: 'Surgical Dislocation' },
      { value: 'SCFE' },
      { value: 'Other' },
    ],
    dependents: [],
  },
  {
    id: 'dummyQ',
    type: 'FR',
    header: 'Dummy',
    text: 'this is an fr question',
    value: [],
    required: true,
    options: [],
    dependents: [],
  },
];
